version: '3.8'
services:
  dev-db:
    restart: always
    container_name: postgres_dev
    image: postgres:13
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - tacohouse
  test-db:
    container_name: postgres_test
    image: postgres:13
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - tacohouse
networks:
  tacohouse:
    driver: bridge
